/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Vitamin (https://sketchfab.com/btrseller)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vr-headset-free-model-51b8dbff65e247979f068914f6197909
Title: VR Headset Free Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material} rotation={[Math.PI / 3.4, .88, .47]}/>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
